site_name: monoLibrary
site_url: https://solar-eos.github.io/monoLibrary/
repo_name: Solar-Eos/monoLibrary
repo_url: https://github.com/Solar-Eos/monoLibrary

theme:
  icon:
    logo: material/database
    repo: fontawesome/brands/git-alt
  name: material
  favicon: images/favicon.png
  palette:
    primary: "Deep Purple"
    accent: "Deep Purple"

nav:
  - Home: readme.md
  - Tutorial:
    - Setting up: tutorial/settingup.md
    - Basic Usage: tutorial/basic_usage.md
    - Developer Products: tutorial/developer_products.md
  - Troubleshooting: troubleshooting.md
  - API: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences